# Generated by Django 2.1.7 on 2019-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=32)),
                ('author', models.CharField(default='Author', max_length=32)),
                ('content', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
