# Generated by Django 2.1.7 on 2019-03-16 17:01

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='content',
            field=mdeditor.fields.MDTextField(null=True),
        ),
    ]
